### ISSUE TITLE
Finding optimal solutions

### ISSUE THREAD

**Issue by simonpuchert** [smack42/ColorFill#1]
I have looked a bit into your code, and while you have nice sub-optimal solvers, the exhaustive search you're doing is a bit slow.
Now, the "true" reason why I came here is because my brother and I are doing something similar (aaronpuchert/floodit). It even has the same license, so you can just rummage through it.
I've done some more work locally (mostly merging the master branch and the performance branch) and the resulting program took about 4 seconds on average for each of the codegolf grids, which would mean ~110 CPU hours in total (that was on a Phenom II x4 965).
From the partial runs I did, I'd expect around 1 986 000 moves for the 100 000 grids.

We use an A*-type algorithm with a heuristic similar to tigrou's (but actually admissible) and move pruning similar to Jump-Point Search.

**Comment by smack42** [comment]
Thank you for your interest in my program! I will have a closer look at your solver algorithm and maybe even port it to Java and do some experiments. That's a great opportunity to learn and improve my coding, thanks! Heuristics are kind of a "black art" so it's always nice when I can have a look at somebody else's ideas.

It's true that my exhaustive search algorithm is very slow, but at least the current version runs more than ten times faster than the initial version, thanks to some algorithm-level optimisations (better pruning) and many low-level improvements (for example, using bitfields). I want to use it to find the optimal solutions as a benchmark for all those sub-optimal solvers out there. For "pc19" that was easy to do because those 1000 14x14 grids can be solved quickly. The "codegolf" test is much more expensive and currently out of reach for my exhaustive solver. Maybe some day, using an improved algorithm and a faster machine...

**Comment by smack42** [comment]
Running your floodit solver now and yes - it's fast and finds optimal solutions! I'm humbled by that great solver performance compared to my sluggish exhaustive DFS. Thanks again for pointing out your better algorithm. I'm going to study it and create my own implementation of it.

**Comment by simonpuchert** [comment]
Hmm, it's actually slower than the exhaustive search, but that might not be a bad thing.
Sadly, I don't really know much about Java, but I can try looking into it if there's a problem with how the data is structured - maybe some of the improvements can even be used to speed up the other solvers.

For the record, on my old CPU (the Phenom), the pc19 1000 14x14 puzzles took 86 seconds of CPU time and on a Ryzen7 1800X it takes 60 seconds of CPU time (performance branch). So that is quite a discrepancy to your numbers.
Also, it's a bit weird that the difference between the CPUs is so small, probably because there is very little to vectorize. Oh well, I still got 4 times the amount of threads. Experiments with threading the computation suggest a total of 8 hours (real time) on all threads for the codegolf challenge, which is still too much for me, but it's close enough for a "piecemeal" approach. If that ever gets done, I'll make sure to inform you of the results.

**Comment by smack42** [comment]
The new AStar strategy is already significantly faster than the exhaustive DFS. In the [history of the pc19 test results file](https://github.com/smack42/ColorFill/commits/master/pc19/results_ColorFill_exhaustive_details.txt) we find the durations: DfsExhaustiveStrategy 2777869 ms, AStarPuchertStrategy 1741488 ms. And that's using my implementation of your "old" heuristic. I have yet to implement your latest "performance" heuristics, which will give it another speed boost. Not sure if that will be an order of magnitude which would be necessary to match the performance of your solver program.

**Comment by smack42** [comment]
Good news! My implementation of your "performance" heuristic is working now and it's quite fast as well. My Java program's AStarPuchertStrategy completes the pc19 test in less than 2 minutes.

Thanks again for the inspiration for such a nice and fast solver algorithm!

**Comment by smack42** [comment]
Note: codegolf26232 test case 934 in input file floodtest is a pathological case.
Currently it can't be solved using AStarPuchertStrategy because the algorithm runs for a very long time until it fails because of OutOfMemoryError.
To be investigated...

**Comment by simonpuchert** [comment]
You're either going to need some further optimizations or more RAM. I ran our program on 16 GB:
14246351632152346136251 (time: 4m49,119s, ~8300MB maximum allocation)

I didn't verify it yet, so it might be wrong, but here you have it.

Oh, and congratulations are in order for your great results.

**Comment by smack42** [comment]
Thanks for this info which encouraged me to optimize my program further. I managed to reduce its memory usage significantly with only a small runtime penalty. Now it can solve that codegolf26232 test case 934, the result is 12163462431561342632156 = 23 steps.
It's still a challenge, requiring several minutes and about 10 GB of memory. Most other test cases can be solved much faster with less memory.

**Comment by smack42** [comment]
codegolf26232 optimal result is 1,985,078 steps!

**Comment by simonpuchert** [comment]
Wow, that must have taken quite a bit of patience and determination.

You can close the issue now (if you want). Should we ever find further improvements, I'll make sure to inform you about them.

Maybe a useful next step would be a good explanation of what the algorithm does and why it works, i.e. proving that the pruning doesn't cut all optimal paths (that's quite easy) and that the heuristic is admissible (if I recall correctly, we could even prove that it is consistent).
Aaron will be here soon(TM) and then we might write a draft (I understand the algorithm well, but I'm really bad at explaining things, so I'm not doing that on my own). Your comments / criticism would be most welcome!

**Comment by smack42** [comment]
Indeed, some patience was necessary. The program worked for about 121 hours on my fairly old computer to find the 100000 solutions, as documented in the detailed result file "steps_.txt".

Ever since I've re-implemented your pruning algorithm and A* heuristic, I tried to think of some improvements, but to no avail. It would be interesting to find an even better heuristic, one that estimates the future costs closer to the actual costs (number of steps).

Anyway, I'm glad that it worked out and we finally have the optimal solutions to that big test data set. And yet another indication that the performance of Java programs can be competitive, compared to C and C++ programs.

I'm definitely interested in your further work on this topic, so when you have an algorithm description or some program improvements then please let me know, thanks!
